[package]
name = "cidr_routing-table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "0.3"
rand = "0.8.4"

[[bench]]
name = "routing_table_bench"
harness = false